name: Deploy SolidJS to Main Domain

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, hera-eye]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build with Bun
        run: |
          export PATH=$HOME/.bun/bin:$HOME/.nvm/versions/node/v24.13.0/bin:$PATH

          bun install
          bun run build

          pm2 delete solid-app || true
          pm2 start "bun x serve -s ./dist -p 3012" --name "solid-app"

      - name: Update Cloudflared Config
        run: |
          DOMAIN="kamisama-v0.my.id"
          PORT="3012"

          if ! grep -q "hostname: $DOMAIN" /etc/cloudflared/config.yml; then
            echo "Adding $DOMAIN to cloudflared config..."
            
            sudo sed -i "/- service: http_status:404/i \  - hostname: $DOMAIN\n    service: http://localhost:$PORT" /etc/cloudflared/config.yml
            
            sudo systemctl restart cloudflared
          else
            echo "Domain $DOMAIN sudah terdaftar di config.yml"
          fi

      - name: Update Cloudflare DNS
        run: |
          cloudflared tunnel route dns 60a8a6fd-c3e6-401c-9dde-947a0262b5f0 kamisama-v0.my.id || true
